### ISSUE TITLE
Customization advice

### ISSUE THREAD

**Issue by GioviQ** [adams85/po#17]
I would like to customize POGenerator to generate po file filtered by context.

I would start adding a new setting in POGeneratorSettings.

Some advice?

**Comment by adams85** [comment]
> to generate po file filtered by context.

Could you elaborate on this? Do you want to generate a PO file which only contains entries with specific text context(s)?

**Comment by GioviQ** [comment]
that's right

**Comment by adams85** [comment]
How about this:

```csharp
var filteredCatalog = new POCatalog(Enumerable
    .AsEnumerable<IPOEntry>(catalog)
    .Where(entry => entry.Key.ContextId == /* your condition here */));

var generator = new POGenerator(new POGeneratorSettings {
{
    // generator options...
});

TextWriter writer = ...;
generator.Generate(writer, filteredCatalog);
writer.Flush();
```

Please keep in mind that the `POCatalog(IEnumerable<IPOEntry> items)` constructor doesn't perform a deep copy, thus `catalog` and `filteredCatalog` will contain the same entry instances. If you don't need further modifications to the entries in `filteredCatalog`, this is perfectly ok for your use case. (Deep copy is a feature under consideration and may be added in a future version.)

**Comment by GioviQ** [comment]
Thank you!
