### ISSUE TITLE
Unescaped double quotes in msgid and msgstr entries

### ISSUE THREAD

**Issue by Lyror** [adams85/po#25]
In the PO Library, I have noticed a common problem with the use of double quotes (") within the msgid and msgstr entries. These double quotes are not properly escaped, which can lead to parsing errors. 

For example

my key value is: `Do you want to remove "House" from the list?`
and my translation is: `Möchtest du "Haus" von der Liste löschen?`

this produces:

```
msgid "Do you want to remove "House" from the list?"
msgstr "Möchtest du "Haus" von der Liste löschen?"
```

I would suggest to escape the double quote characters

```
msgid "Do you want to remove \"House\" from the list?"
msgstr "Möchtest du \"Haus\" von der Liste löschen?"
```

**Comment by adams85** [comment]
I'm unable to reproduce this issue using the latest version.

```cs
var catalog = new POCatalog
{
    new POSingularEntry(new POKey("Do you want to remove \"House\" from the list?"))
    {
        Translation = "Möchtest du \"Haus\" von der Liste löschen?"
    },
};

var sb = new StringBuilder();
new POGenerator(new POGeneratorSettings { IgnoreEncoding = true }).Generate(sb, catalog);
var generated = sb.ToString();
```

produces the expected result, double quotes are escaped properly.

Could you provide a minimal repro example/app?

**Comment by Lyror** [comment]
Sry for this issue-creation after further investigation I have identified the problem as a business logic error. The library is working fine as intended. Sorry for this inconvenience. The ticket can be closed.
